# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "33c0b43fe391b9e710d0b2c3ca34fa0e"
name = "Auto Hide Out of Stock"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
